name: CI/CD Pipeline for MediTrack

on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        

        steps:
            - name: Checkout project code  
              uses: actions/checkout@v3   # This is a custom github action that pull the latest code.

            
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20

            - name: Install dependencies
              run: |
                npm install
                cd frontend

            - name: Build the app
              run: npm run build
