name: CI/CD Pipeline for MediTrack
on:
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        

        steps:
            - name: Testing 
              run: echo "Hello world"

            
            - name: Pass the job
              run: exit 0